export interface UKMEntry {
  short: string;
  name: string;
  hasGame: boolean;
  emoji: string;
  desc: string;
  stars: { x: number; y: number }[];
  links: [number, number][];
  gameType?: "quiz" | "reaction" | "runner" | "archery" | "volley" | "placeholder";
  quizQuestions?: { q: string; opts: string[]; ans: number }[];
}

export interface OrbitGroup {
  id: string;
  name: string;
  color: string;
  glow: string;
  desc: string;
  emoji: string;
  planetBg: string;
  planetShadow: string;
  ukms: UKMEntry[];
}

export const ORBIT_GROUPS: OrbitGroup[] = [
  {
    id: "rohani",
    name: "Rohani",
    color: "#06b6d4",
    glow: "rgba(6,182,212,0.3)",
    desc: "Spiritualitas & Nilai",
    emoji: "☮️",
    planetBg: "radial-gradient(circle at 35% 35%, #2dd4bf, #0891b2 40%, #083344 80%)",
    planetShadow: "0 0 30px rgba(6,182,212,0.5), inset -8px -8px 20px rgba(0,0,0,0.4)",
    ukms: [
      {
        short: "JS",
        name: "Jamaah Shalahuddin",
        hasGame: true,
        emoji: "🕌",
        desc: "Komunitas islami dengan kajian rutin, dakwah kampus, dan kegiatan sosial bermakna.",
        stars: [{ x: 0, y: -50 }, { x: 35, y: -15 }, { x: 22, y: 30 }, { x: -22, y: 30 }, { x: -35, y: -15 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0], [0, 2], [0, 3]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Apa arti 'Shalahuddin' dalam bahasa Arab?", opts: ["Kejujuran", "Kebenaran agama", "Perdamaian", "Kemuliaan"], ans: 1 },
          { q: "Kegiatan rutin Jamaah Shalahuddin yang paling terkenal?", opts: ["Latihan voli", "Kajian mingguan", "Pameran seni", "Hiking"], ans: 1 },
          { q: "Masjid kampus UGM bernama?", opts: ["Al-Azhar", "Kampus Raya", "Mujahidin", "Shalahuddin"], ans: 3 },
        ],
      },
      {
        short: "KMHD",
        name: "KM Hindu Dharma UGM",
        hasGame: true,
        emoji: "🌸",
        desc: "Pelestarian budaya, seni, dan nilai Dharma bagi mahasiswa Hindu di UGM.",
        stars: [{ x: 0, y: -45 }, { x: -38, y: 18 }, { x: 38, y: 18 }, { x: 0, y: 0 }],
        links: [[0, 1], [0, 2], [1, 2], [0, 3], [1, 3], [2, 3]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Kitab suci agama Hindu adalah?", opts: ["Al-Quran", "Injil", "Weda", "Tripitaka"], ans: 2 },
          { q: "Hari raya terbesar Hindu adalah?", opts: ["Nyepi", "Galungan", "Kuningan", "Saraswati"], ans: 0 },
          { q: "KMHD singkatan dari?", opts: ["Keluarga Muda Hindu Dharma", "Komunitas Mahasiswa Hindu Dharma", "Keluarga Mahasiswa Hindu Dharma", "KM Hindu Dharma"], ans: 2 },
        ],
      },
      {
        short: "MK UGM",
        name: "Misa Kampus UGM",
        hasGame: false,
        emoji: "✝️",
        desc: "Pelayanan rohani Katolik dengan misa kampus, retret, dan bakti sosial.",
        stars: [{ x: 0, y: -50 }, { x: 0, y: 50 }, { x: -40, y: 0 }, { x: 40, y: 0 }, { x: 0, y: 0 }],
        links: [[0, 4], [4, 1], [2, 4], [4, 3]],
        gameType: "placeholder",
      },
      {
        short: "KMK",
        name: "Keluarga Mahasiswa Kristen",
        hasGame: false,
        emoji: "🌿",
        desc: "Persekutuan mahasiswa Kristen yang berfokus pada pelayanan dan pengembangan iman.",
        stars: [{ x: 0, y: -40 }, { x: 38, y: -12 }, { x: 23, y: 38 }, { x: -23, y: 38 }, { x: -38, y: -12 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0]],
        gameType: "placeholder",
      },
      {
        short: "PMKRI",
        name: "PM Katolik RI UGM",
        hasGame: false,
        emoji: "🌐",
        desc: "Organisasi mahasiswa Katolik yang aktif dalam gerakan sosial dan kepemimpinan.",
        stars: [{ x: 0, y: -50 }, { x: 43, y: -22 }, { x: 27, y: 42 }, { x: -27, y: 42 }, { x: -43, y: -22 }, { x: 0, y: 12 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0], [0, 5], [2, 5], [4, 5]],
        gameType: "placeholder",
      },
    ],
  },
  {
    id: "olahraga",
    name: "Olahraga",
    color: "#f97316",
    glow: "rgba(249,115,22,0.3)",
    desc: "Atletik & Kompetisi",
    emoji: "🏐",
    planetBg: "radial-gradient(circle at 30% 30%, #fed7aa, #f97316 40%, #7c2d12 80%)",
    planetShadow: "0 0 30px rgba(249,115,22,0.5), inset -8px -8px 20px rgba(0,0,0,0.4)",
    ukms: [
      {
        short: "BERKUDA",
        name: "UKM Berkuda UGM",
        hasGame: true,
        emoji: "🐎",
        desc: "UKM Berkuda UGM jadi ruang buat melatih fokus, keseimbangan, dan chemistry antara penunggang dengan kudanya. Di mini game ini, Gilang menunggang kuda dan berlari otomatis di lintasan yang makin cepat, jadi kamu harus jeli menentukan timing lompatan untuk melewati rintangan yang makin rapat dan menantang.",
        stars: [{ x: -40, y: 10 }, { x: -18, y: -32 }, { x: 16, y: -30 }, { x: 42, y: 4 }, { x: 10, y: 34 }, { x: -18, y: 32 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0], [1, 5], [2, 4]],
        gameType: "runner",
      },
      {
        short: "PANAHAN",
        name: "UKM Panahan UGM",
        hasGame: true,
        emoji: "🏹",
        desc: "UKM Panahan UGM identik dengan ketenangan, kontrol napas, dan akurasi. Mini game panahan ini meniru momen latihan bidik: kamu menahan untuk menarik busur, mengatur tenaga, lalu melepas panah pada saat yang paling pas ketika target bergerak naik turun di arena.",
        stars: [{ x: 0, y: -48 }, { x: 36, y: -18 }, { x: 32, y: 24 }, { x: 0, y: 42 }, { x: -32, y: 24 }, { x: -36, y: -18 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0], [0, 3], [1, 4]],
        gameType: "archery",
      },
      {
        short: "VOLI",
        name: "UKM Voli UGM",
        hasGame: true,
        emoji: "🏐",
        desc: "UKM Voli UGM menonjolkan koordinasi tim, refleks cepat, dan timing serangan yang presisi. Di mini game ini, setter akan mengangkat bola dengan sudut yang berubah-ubah pada tiap rally, lalu kamu harus klik tepat di momen emas untuk menghasilkan spike yang bersih dan bertenaga.",
        stars: [{ x: -40, y: -8 }, { x: -18, y: -38 }, { x: 18, y: -38 }, { x: 40, y: -8 }, { x: 24, y: 34 }, { x: -24, y: 34 }, { x: 0, y: 8 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0], [1, 6], [2, 6], [4, 6], [5, 6]],
        gameType: "volley",
      },
      {
        short: "BASKET",
        name: "UKM Basket UGM",
        hasGame: false,
        emoji: "🏀",
        desc: "UKM Basket UGM tetap tampil di peta olahraga sebagai bagian dari konstelasi cabang yang aktif. Mini game khusus basket belum dibuat pada versi ini, tetapi kartunya sudah disiapkan supaya nanti bisa langsung diisi mode permainan yang lebih kompetitif.",
        stars: [{ x: 0, y: -48 }, { x: 36, y: -15 }, { x: 22, y: 35 }, { x: -22, y: 35 }, { x: -36, y: -15 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0], [0, 2], [0, 3]],
        gameType: "placeholder",
      },
      {
        short: "ESPORTS",
        name: "Esports UGM",
        hasGame: false,
        emoji: "🎮",
        desc: "Esports UGM hadir sebagai bagian dari spektrum olahraga modern yang berkembang cepat di kampus. Untuk sekarang mini game-nya masih placeholder, jadi saat dipilih akan muncul penanda bahwa mode bermainnya belum tersedia pada build ini.",
        stars: [{ x: -45, y: -5 }, { x: -20, y: -35 }, { x: 0, y: -45 }, { x: 20, y: -35 }, { x: 45, y: -5 }, { x: 35, y: 35 }, { x: -35, y: 35 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 0], [1, 6], [3, 5]],
        gameType: "placeholder",
      },
      {
        short: "BULU",
        name: "UKM Bulutangkis",
        hasGame: false,
        emoji: "🏸",
        desc: "UKM Bulutangkis tetap dipertahankan di peta olahraga supaya susunan rasi bintangnya tetap lengkap. Mode permainan untuk cabang ini belum dibuat, tetapi ruangnya sudah ada dan siap dikembangkan di update berikutnya.",
        stars: [{ x: 0, y: -48 }, { x: -18, y: -10 }, { x: 0, y: 5 }, { x: 18, y: -10 }, { x: -22, y: 38 }, { x: 22, y: 38 }],
        links: [[0, 1], [0, 3], [1, 2], [3, 2], [2, 4], [2, 5], [4, 5]],
        gameType: "placeholder",
      },
      {
        short: "RENANG",
        name: "UKM Renang UGM",
        hasGame: false,
        emoji: "🏊",
        desc: "UKM Renang UGM mewakili cabang yang menuntut stamina, teknik, dan ritme gerak yang konsisten. Pada versi saat ini mini game renang belum tersedia, namun node-nya tetap muncul agar keseluruhan peta olahraga tidak kehilangan konteks.",
        stars: [{ x: -50, y: 0 }, { x: -25, y: -25 }, { x: 0, y: 10 }, { x: 25, y: -25 }, { x: 50, y: 0 }, { x: 0, y: 35 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [0, 2], [2, 4], [2, 5]],
        gameType: "placeholder",
      },
      {
        short: "SEPAK BOLA",
        name: "UKM Sepak Bola UGM",
        hasGame: false,
        emoji: "⚽",
        desc: "UKM Sepak Bola UGM masih diposisikan sebagai placeholder di peta olahraga. Mini game-nya belum dibuat pada versi ini, tetapi informasi dan titik konstelasinya sengaja tetap ditampilkan agar cabang populer ini tidak terasa hilang dari simulasi.",
        stars: [{ x: 0, y: -48 }, { x: 45, y: -15 }, { x: 28, y: 40 }, { x: -28, y: 40 }, { x: -45, y: -15 }, { x: 0, y: 10 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0], [0, 5], [2, 5], [4, 5]],
        gameType: "placeholder",
      },
    ],
  },
  {
    id: "seni",
    name: "Seni",
    color: "#a855f7",
    glow: "rgba(168,85,247,0.3)",
    desc: "Kreasi & Ekspresi",
    emoji: "🎨",
    planetBg: "radial-gradient(circle at 35% 30%, #e9d5ff, #a855f7 40%, #3b0764 80%)",
    planetShadow: "0 0 30px rgba(168,85,247,0.5), inset -8px -8px 20px rgba(0,0,0,0.4)",
    ukms: [
      {
        short: "TGM",
        name: "Tari Gaya Yogyakarta",
        hasGame: true,
        emoji: "💃",
        desc: "Unit tari tradisional Yogyakarta yang melestarikan seni gerak dengan jiwa kontemporer.",
        stars: [{ x: 0, y: -48 }, { x: -30, y: -20 }, { x: -45, y: 15 }, { x: -15, y: 35 }, { x: 15, y: 35 }, { x: 45, y: 15 }, { x: 30, y: -20 }],
        links: [[0, 1], [0, 6], [1, 2], [6, 5], [2, 3], [5, 4], [3, 4], [1, 3], [6, 4]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Tari Bedhaya adalah tari istana yang berasal dari?", opts: ["Bali", "Yogyakarta", "Surakarta", "Jawa Timur"], ans: 1 },
          { q: "Kostum tari tradisional Jawa biasanya menggunakan?", opts: ["Kain batik", "Kain tenun", "Kain songket", "Kain lurik"], ans: 0 },
          { q: "Gerakan dasar tari Jawa yang paling dikenal adalah?", opts: ["Ngithing", "Ngembat", "Kebyar", "Tandak"], ans: 0 },
        ],
      },
      {
        short: "PSM",
        name: "Paduan Suara Mahasiswa",
        hasGame: true,
        emoji: "🎵",
        desc: "Komunitas vokal yang sering tampil di acara nasional dan internasional.",
        stars: [{ x: 0, y: -50 }, { x: 0, y: 5 }, { x: -18, y: 20 }, { x: -10, y: 40 }, { x: 0, y: 45 }, { x: 10, y: 40 }, { x: 18, y: 20 }],
        links: [[0, 1], [1, 2], [1, 6], [2, 3], [6, 5], [3, 4], [5, 4]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Paduan suara yang menyanyi tanpa iringan alat musik disebut?", opts: ["Acapella", "Choir", "Ensemble", "Quartet"], ans: 0 },
          { q: "Suara tertinggi dalam paduan suara campuran adalah?", opts: ["Alto", "Tenor", "Sopran", "Bass"], ans: 2 },
          { q: "PSM UGM sering tampil di acara?", opts: ["Dies Natalis UGM", "Upacara Wisuda", "Kedua-duanya", "Tidak pernah tampil"], ans: 2 },
        ],
      },
      {
        short: "UFO",
        name: "UFO Teater UGM",
        hasGame: true,
        emoji: "🎭",
        desc: "Unit teater yang mengangkat isu sosial lewat panggung kreatif dan pertunjukan memukau.",
        stars: [{ x: -45, y: -20 }, { x: -25, y: -40 }, { x: 0, y: -48 }, { x: 25, y: -40 }, { x: 45, y: -20 }, { x: 35, y: 28 }, { x: -35, y: 28 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 0]],
        gameType: "placeholder",
      },
      {
        short: "KFUGM",
        name: "UKM Fotografi UGM",
        hasGame: false,
        emoji: "📷",
        desc: "Komunitas sineas dan fotografer yang aktif memproduksi karya berkualitas.",
        stars: [{ x: -40, y: -25 }, { x: 40, y: -25 }, { x: 45, y: 30 }, { x: -45, y: 30 }, { x: 0, y: 5 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 0], [0, 4], [1, 4], [2, 4], [3, 4]],
        gameType: "placeholder",
      },
      {
        short: "SENI RUPA",
        name: "UKM Seni Rupa UGM",
        hasGame: false,
        emoji: "🖼️",
        desc: "Komunitas seni rupa yang aktif berpameran dan menciptakan karya visual inovatif.",
        stars: [{ x: -30, y: -40 }, { x: 30, y: -40 }, { x: 50, y: 5 }, { x: 20, y: 42 }, { x: -20, y: 42 }, { x: -50, y: 5 }],
        links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0], [0, 3], [1, 4]],
        gameType: "placeholder",
      },
    ],
  },
  {
    id: "khusus",
    name: "Khusus",
    color: "#10b981",
    glow: "rgba(16,185,129,0.3)",
    desc: "Minat & Kepemimpinan",
    emoji: "🔬",
    planetBg: "radial-gradient(circle at 35% 35%, #a7f3d0, #10b981 40%, #064e3b 80%)",
    planetShadow: "0 0 30px rgba(16,185,129,0.5), inset -8px -8px 20px rgba(0,0,0,0.4)",
    ukms: [
      {
        short: "MAPAGAMA",
        name: "Mahasiswa Pecinta Alam",
        hasGame: true,
        emoji: "🏔️",
        desc: "Komunitas ekspedisi dan konservasi alam dengan jiwa petualang dan cinta lingkungan.",
        stars: [{ x: 0, y: -50 }, { x: -40, y: 25 }, { x: 40, y: 25 }, { x: -20, y: 10 }, { x: 20, y: 10 }],
        links: [[0, 3], [0, 4], [3, 1], [4, 2], [1, 2], [3, 4]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Mapagama singkatan dari?", opts: ["Mahasiswa Pencinta Alam Gadjah Mada", "Mahasiswa Pecinta Alam Gadjah Mada", "Mahasiswa Penjelajah Alam Gadjah Mada", "Masyarakat Pecinta Alam Gadjah Mada"], ans: 1 },
          { q: "Prinsip dasar pecinta alam adalah?", opts: ["Tinggalkan jejak sebanyak mungkin", "Tinggalkan sampahmu di alam", "Leave no trace — jaga alam", "Bawa pulang flora dan fauna"], ans: 2 },
          { q: "Alat wajib mendaki gunung adalah?", opts: ["Payung", "Jas hujan dan kompas", "Sepatu kasual", "Topi pantai"], ans: 1 },
        ],
      },
      {
        short: "KOPMA",
        name: "Koperasi Mahasiswa UGM",
        hasGame: true,
        emoji: "💼",
        desc: "Koperasi mahasiswa yang melatih jiwa wirausaha dan manajemen bisnis nyata.",
        stars: [{ x: -48, y: -15 }, { x: 0, y: -15 }, { x: 48, y: -15 }, { x: 0, y: -15 }, { x: 0, y: 40 }, { x: -30, y: 28 }, { x: 30, y: 28 }],
        links: [[0, 1], [1, 2], [1, 4], [1, 5], [1, 6], [5, 6], [4, 5], [4, 6]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Prinsip dasar koperasi adalah?", opts: ["Profit semaksimal mungkin", "Dari, oleh, dan untuk anggota", "Persaingan bebas", "Monopoli pasar"], ans: 1 },
          { q: "Koperasi di Indonesia diatur dalam UU nomor?", opts: ["UU No. 17/2012", "UU No. 25/1992", "UU No. 5/1960", "UU No. 13/2003"], ans: 1 },
          { q: "SHU koperasi dibagi berdasarkan?", opts: ["Modal awal anggota", "Partisipasi transaksi anggota", "Jabatan pengurus", "Lama bergabung"], ans: 1 },
        ],
      },
      {
        short: "UKESMA",
        name: "UKM Pers Mahasiswa",
        hasGame: true,
        emoji: "📰",
        desc: "Unit pers mahasiswa yang aktif menulis, meliput, dan menerbitkan media kampus.",
        stars: [{ x: 0, y: -50 }, { x: -20, y: -15 }, { x: 0, y: -5 }, { x: 20, y: -15 }, { x: 0, y: 45 }],
        links: [[0, 1], [0, 3], [1, 2], [3, 2], [2, 4]],
        gameType: "quiz",
        quizQuestions: [
          { q: "Kode etik jurnalistik mengharuskan wartawan untuk?", opts: ["Berpihak pada satu pihak", "Berimbang dan cover both sides", "Menyembunyikan fakta", "Mengutamakan opini pribadi"], ans: 1 },
          { q: "Lead (teras berita) yang baik harus mengandung?", opts: ["5W1H", "Opini redaksi", "Iklan produk", "Biografi penulis"], ans: 0 },
          { q: "Berita yang menyebarkan informasi palsu disebut?", opts: ["Breaking news", "Feature", "Hoaks", "Editorial"], ans: 2 },
        ],
      },
      {
        short: "KSI",
        name: "Kelompok Studi Islam",
        hasGame: false,
        emoji: "🔬",
        desc: "Forum keilmuan dan riset interdisipliner yang mendalami kajian Islam kontemporer.",
        stars: [{ x: 0, y: -20 }, { x: -40, y: -40 }, { x: 40, y: -40 }, { x: -40, y: 30 }, { x: 40, y: 30 }],
        links: [[0, 1], [0, 2], [0, 3], [0, 4], [1, 3], [2, 4]],
        gameType: "placeholder",
      },
      {
        short: "PRAMUKA",
        name: "Pramuka UGM",
        hasGame: false,
        emoji: "⚜️",
        desc: "Gerakan pramuka universitas yang menempa karakter, kepemimpinan, dan pengabdian.",
        stars: [{ x: 0, y: -50 }, { x: -22, y: -18 }, { x: 0, y: -5 }, { x: 22, y: -18 }, { x: 15, y: 32 }, { x: -15, y: 32 }, { x: 0, y: 42 }],
        links: [[0, 1], [0, 3], [1, 2], [3, 2], [2, 4], [2, 5], [4, 6], [5, 6]],
        gameType: "placeholder",
      },
    ],
  },
];
