import type { AppLanguage } from "@/components/LanguageProvider";

export function tr(lang: AppLanguage, id: string, en: string) {
  return lang === "en" ? en : id;
}

const DYNAMIC_TRANSLATIONS: Record<string, string> = {
  "Beranda": "Home",
  "Simulasi UKM": "UKM Simulation",
  "Bilik Foto": "Photo Booth",
  "Simulasi": "Simulation",
  "Jika kamu memiliki keterbatasan penglihatan, tekan layar dua kali untuk mengaktifkan fitur pembaca layar. Kami akan membantumu menjelajahi website ini dengan mudah.": "If you have visual impairments, tap this screen twice to activate the screen reader. We will help you navigate this website easily.",
  "tekan di mana saja": "tap anywhere",
  "sekali lagi, TTS langsung aktif": "one more tap, TTS will activate",
  "Saya tidak memerlukan pembaca layar": "I do not need the screen reader",
  "AKSESIBILITAS": "ACCESSIBILITY",
  "Halaman saat ini": "Current page",
  "Hentikan": "Stop",
  "Baca Halaman Ini": "Read This Page",
  "Gunakan headphone untuk pengalaman terbaik": "Use headphones for the best experience",
  "PILIH UKM-MU": "CHOOSE YOUR UKM",
  "TEMUKAN": "FIND",
  "Geser kartu UKM seperti main Tinder — ke kanan kalau tertarik, ke kiri kalau skip, ke atas kalau mau tahu lebih.": "Swipe UKM cards like Tinder — right if interested, left to skip, up if you want to know more.",
  "Skip": "Skip",
  "Info": "Info",
  "Tertarik": "Interested",
  "Start Swiping": "Start Swiping",
  "PREFERENSI": "PREFERENCE",
  "SWIPE SESSION": "SWIPE SESSION",
  "tersisa": "left",
  "Geser kartu atau gunakan tombol di atas": "Swipe the cards or use the buttons above",
  "HASIL MATCH": "MATCH RESULT",
  "UKM TERBAIK UNTUKMU": "BEST UKM FOR YOU",
  "tertarik": "interested",
  "ingin tahu": "curious",
  "skip": "skipped",
  "MATCH": "MATCH",
  "Rekomendasi Lain": "Other Recommendations",
  "UKM yang kamu suka ❤️": "UKMs you liked ❤️",
  "Coba Lagi": "Try Again",
  "Klik planet untuk melihat rasi bintang UKM-nya! ✨": "Click a planet to view its UKM constellation! ✨",
  "ORBIT GALAKSI UKM": "UKM GALAXY ORBIT",
  "PETA RASI BINTANG": "CONSTELLATION MAP",
  "Hover untuk melihat · Klik untuk bermain": "Hover to preview · Click to play",
  "Klik untuk bermain mini game →": "Click to play mini game →",
  "SEGERA HADIR!": "COMING SOON!",
  "sedang dikembangkan.": "is being developed.",
  "Kembali": "Back",
  "Main Mini Game": "Play Mini Game",
  "Skor:": "Score:",
  "Sempurna!": "Perfect!",
  "Bagus sekali!": "Great job!",
  "Terus belajar!": "Keep learning!",
  "Ulangi": "Retry",
  "Ketuk item yang muncul secepat mungkin!": "Tap the item that appears as fast as you can!",
  "30 detik · Klik secepat mungkin": "30 seconds · Click as fast as you can",
  "Mulai": "Start",
  "Luar biasa!": "Amazing!",
  "Bagus!": "Good!",
  "Coba lagi!": "Try again!",
  "BILIK FOTO": "PHOTO BOOTH",
  "PILIH FILTER UKM-MU": "CHOOSE YOUR UKM FILTER",
  "Pilih filter favoritmu, lalu foto bersama teman!": "Choose your favorite filter, then take photos with your friends!",
  "4 foto · countdown 3 detik tiap foto": "4 photos · 3-second countdown for each shot",
  "Mulai Foto": "Start Photo Session",
  "SESI FOTO": "PHOTO SESSION",
  "Mulai Sesi": "Start Session",
  "Bersiap…": "Get ready…",
  "Klik!": "Click!",
  "Mengambil foto": "Capturing photo",
  "HASIL FOTO": "PHOTO RESULTS",
  "FOTO KAMU SIAP!": "YOUR PHOTOS ARE READY!",
  "Download strip foto atau foto individual": "Download the photo strip or individual photos",
  "Strip PNG": "PNG Strip",
  "Download Strip": "Download Strip",
  "Foto": "Photo",
  "Pilih Filter Lain": "Choose Another Filter",
  "Foto Lagi": "Take More Photos",
  "LAGU GELEX 2026": "GELEX 2026 SONG",
  "Anthem resmi Gelanggang Expo UGM 2026": "The official anthem of Gelanggang Expo UGM 2026",
  "Anthem Resmi · Gelanggang Expo UGM": "Official Anthem · Gelanggang Expo UGM",
  "Mulai ulang": "Restart",
  "LIRIK · BAHASA INDONESIA": "LYRICS · INDONESIAN",
  "LIRIK · ENGLISH": "LYRICS · ENGLISH",
  "Berbicara…": "Speaking…",
  "Klik lirik untuk loncat ke bagian tersebut · Klik TTS untuk dengar lirik saat ini": "Click a lyric line to jump there · Click TTS to hear the current lyric",
  "TENTANG GELEX": "ABOUT GELEX",
  "MISI GALAKSI 2026": "GALAXY MISSION 2026",
  "Mulai Sekarang": "Start Now",
  "Tanggal": "Date",
  "Lokasi": "Location",
  "Tema": "Theme",
  "UKM Hadir": "UKMs Present",
  "3 Hari": "3 Days",
  "Fitur Digital": "Digital Features",
  "JELAJAHI SEBELUM HADIR": "EXPLORE BEFORE YOU ARRIVE",
  "EKSPLORASI DIGITAL GELEX 2026": "GELEX 2026 DIGITAL EXPLORATION",
  "Jelajahi →": "Explore →",
  "Lihat Lirik →": "View Lyrics →",
  "Pemutar Anthem": "Anthem Player",
  "Kegiatan yang bikin kamu semangat?": "What kind of activities get you excited?",
  "Gerak & tantangan fisik": "Movement & physical challenges",
  "Eksplorasi kreatif & seni": "Creative exploration & arts",
  "Ngobrol, kolaborasi, komunitas": "Chatting, collaboration, community",
  "Belajar & riset hal baru": "Learning & researching new things",
  "Kamu lebih nyaman di posisi mana?": "Which role feels most comfortable for you?",
  "Tampil di depan / panggung": "Performing in front / on stage",
  "Behind the scenes / teknis": "Behind the scenes / technical",
  "Pemimpin & pengorganisir": "Leader & organizer",
  "Pengabdi setia & sukarelawan": "Dedicated helper & volunteer",
  "Vibe lingkungan yang kamu mau?": "What kind of environment do you want?",
  "Alam & udara segar": "Nature & fresh air",
  "Kompetisi & menang": "Competition & winning",
  "Komunitas hangat & rohani": "Warm & spiritual community",
  "Studio & ruang berkreasi": "Studio & creative space",
  "Suara": "Voice",
  "Harmoni": "Harmony",
  "Panggung": "Stage",
  "Tim": "Team",
  "Smes": "Spike",
  "Turnamen": "Tournament",
  "Ekspedisi": "Expedition",
  "Alam": "Nature",
  "Survival": "Survival",
  "Dakwah": "Da'wah",
  "Ukhuwah": "Brotherhood",
  "Kajian": "Study",
  "Akting": "Acting",
  "Drama": "Drama",
  "Ekspresi": "Expression",
  "Dribble": "Dribble",
  "Slam Dunk": "Slam Dunk",
  "Liga": "League",
  "Iman": "Faith",
  "Komunitas": "Community",
  "Pelayanan": "Service",
  "Frame": "Frame",
  "Momen": "Moment",
  "Estetika": "Aesthetics",
  "Gaming": "Gaming",
  "Strategi": "Strategy",
  "Tournament": "Tournament",
  "Donor Darah": "Blood Donation",
  "P3K": "First Aid",
  "Baksos": "Social Service",
  "Menyelam": "Diving",
  "Laut": "Sea",
  "Eksplorasi": "Exploration",
  "Sinema": "Cinema",
  "Sutradara": "Director",
  "Cerita": "Story",
  "Klasik": "Classic",
  "Gerak": "Movement",
  "Budaya": "Culture",
  "Kata": "Kata",
  "Kumite": "Kumite",
  "Disiplin": "Discipline",
  "Argumen": "Argument",
  "Logika": "Logic",
  "Kompetisi": "Competition",
  "Bisnis": "Business",
  "Koperasi": "Cooperative",
  "Wirausaha": "Entrepreneurship",
  "Hindu": "Hindu",
  "Dharma": "Dharma",
  "Smash": "Smash",
  "Rally": "Rally",
  "Agility": "Agility",
  "Paduan suara mahasiswa bergengsi, tampil di panggung nasional hingga internasional.": "A prestigious student choir performing on national and international stages.",
  "Spike keras, kerja tim solid, dan semangat juang yang nggak pernah padam.": "Powerful spikes, solid teamwork, and a fighting spirit that never fades.",
  "Mendaki puncak, menyusuri gua, dan menjelajahi alam liar bersama komunitas tangguh.": "Climb summits, explore caves, and venture into the wild with a resilient community.",
  "Komunitas Islam terbesar UGM, aktif dalam dakwah, kajian, dan pengabdian masyarakat.": "UGM's largest Islamic community, active in da'wah, study circles, and community service.",
  "Pentas teatrikal yang memadukan seni peran, sastra, dan kritik sosial.": "Theatrical performances blending acting, literature, and social critique.",
  "Lapangan basket, keringat, dan chemistry tim yang terbangun lewat latihan intens.": "Basketball courts, sweat, and team chemistry built through intense training.",
  "Keluarga Mahasiswa Kristen yang hangat, aktif dalam pelayanan dan pengembangan diri.": "A warm Christian student fellowship active in service and self-growth.",
  "Mengabadikan keindahan dunia lewat lensa, dari street photography hingga portrait.": "Capture the beauty of the world through a lens, from street photography to portraits.",
  "Bertarung di dunia digital — MLBB, Valorant, hingga turnamen nasional.": "Compete in the digital arena—from MLBB and Valorant to national tournaments.",
  "Korps sukarelawan yang siap siaga, berdedikasi menolong sesama kapan pun dibutuhkan.": "A ready volunteer corps dedicated to helping others whenever needed.",
  "Menyelami kedalaman laut, menjelajahi terumbu karang, dan merasakan bebas di bawah air.": "Dive into the ocean depths, explore coral reefs, and feel free underwater.",
  "Dari ide ke layar lebar — produksi film pendek, dokumenter, dan festival film mahasiswa.": "From idea to big screen—produce short films, documentaries, and student film festivals.",
  "Pelestarian seni tari Jawa klasik yang anggun — dari Bedhaya hingga tari kontemporer.": "Preserving graceful classical Javanese dance—from Bedhaya to contemporary dance.",
  "Seni bela diri yang membangun fisik, mental, dan karakter juara.": "A martial art that builds body, mind, and a champion's character.",
  "Asah kemampuan berpikir kritis dan berbicara meyakinkan di panggung debat internasional.": "Sharpen critical thinking and persuasive speaking on international debate stages.",
  "Belajar bisnis nyata dari kampus — koperasi mahasiswa terbesar dengan usaha aktif.": "Learn real business on campus through the largest student cooperative with active ventures.",
  "Wadah mahasiswa Hindu UGM untuk pengembangan spiritual, budaya, dan persaudaraan.": "A space for Hindu students at UGM to grow spiritually, culturally, and in fellowship.",
  "Dari latihan rutin hingga kompetisi nasional — ayo buktikan skill di lapangan!": "From regular practice to national competitions—prove your skills on the court!",
  "Rohani": "Spiritual",
  "Olahraga": "Sports",
  "Seni": "Arts",
  "Khusus": "Special",
  "Spiritualitas & Nilai": "Spirituality & Values",
  "Atletik & Kompetisi": "Athletics & Competition",
  "Kreasi & Ekspresi": "Creativity & Expression",
  "Minat & Kepemimpinan": "Interests & Leadership",
  "Komunitas islami dengan kajian rutin, dakwah kampus, dan kegiatan sosial bermakna.": "An Islamic community with regular study circles, campus da'wah, and meaningful social activities.",
  "Pelestarian budaya, seni, dan nilai Dharma bagi mahasiswa Hindu di UGM.": "Preservation of culture, arts, and Dharma values for Hindu students at UGM.",
  "Pelayanan rohani Katolik dengan misa kampus, retret, dan bakti sosial.": "Catholic spiritual service with campus mass, retreats, and social outreach.",
  "Persekutuan mahasiswa Kristen yang berfokus pada pelayanan dan pengembangan iman.": "A Christian student fellowship focused on ministry and faith development.",
  "Organisasi mahasiswa Katolik yang aktif dalam gerakan sosial dan kepemimpinan.": "A Catholic student organization active in social movements and leadership.",
  "Tim voli kompetitif yang aktif di liga antar universitas nasional.": "A competitive volleyball team active in national inter-university leagues.",
  "Tim basket dengan prestasi di kejuaraan nasional universitas Indonesia.": "A basketball team with achievements in national university championships.",
  "Tim esports kompetitif aktif di turnamen nasional dan internasional.": "A competitive esports team active in national and international tournaments.",
  "Komunitas bulutangkis yang aktif berlatih dan mengikuti berbagai turnamen.": "A badminton community that trains actively and joins various tournaments.",
  "Komunitas renang yang melatih teknik dan stamina di kolam renang UGM.": "A swimming community that trains technique and stamina at the UGM pool.",
  "Tim sepak bola UGM yang aktif dalam kompetisi antar universitas.": "UGM's football team active in inter-university competitions.",
  "Unit tari tradisional Yogyakarta yang melestarikan seni gerak dengan jiwa kontemporer.": "A Yogyakarta traditional dance unit preserving movement arts with a contemporary spirit.",
  "Komunitas vokal yang sering tampil di acara nasional dan internasional.": "A vocal community that often performs at national and international events.",
  "Unit teater yang mengangkat isu sosial lewat panggung kreatif dan pertunjukan memukau.": "A theater unit raising social issues through creative stages and captivating performances.",
  "Komunitas sineas dan fotografer yang aktif memproduksi karya berkualitas.": "A community of filmmakers and photographers actively producing quality work.",
  "Komunitas seni rupa yang aktif berpameran dan menciptakan karya visual inovatif.": "A visual arts community active in exhibitions and innovative visual works.",
  "Komunitas ekspedisi dan konservasi alam dengan jiwa petualang dan cinta lingkungan.": "An expedition and conservation community with an adventurous spirit and love for nature.",
  "Koperasi mahasiswa yang melatih jiwa wirausaha dan manajemen bisnis nyata.": "A student cooperative that trains entrepreneurship and real business management.",
  "Unit pers mahasiswa yang aktif menulis, meliput, dan menerbitkan media kampus.": "A student press unit active in writing, reporting, and publishing campus media.",
  "Forum keilmuan dan riset interdisipliner yang mendalami kajian Islam kontemporer.": "An interdisciplinary study and research forum exploring contemporary Islamic studies.",
  "Gerakan pramuka universitas yang menempa karakter, kepemimpinan, dan pengabdian.": "A university scout movement shaping character, leadership, and service.",
  "Apa arti 'Shalahuddin' dalam bahasa Arab?": "What does 'Shalahuddin' mean in Arabic?",
  "Kejujuran": "Honesty",
  "Kebenaran agama": "Religious righteousness",
  "Perdamaian": "Peace",
  "Kemuliaan": "Glory",
  "Kegiatan rutin Jamaah Shalahuddin yang paling terkenal?": "What regular activity is Jamaah Shalahuddin best known for?",
  "Latihan voli": "Volleyball practice",
  "Kajian mingguan": "Weekly study session",
  "Pameran seni": "Art exhibition",
  "Hiking": "Hiking",
  "Masjid kampus UGM bernama?": "What is the name of UGM's campus mosque?",
  "Kitab suci agama Hindu adalah?": "What is the holy scripture of Hinduism?",
  "Al-Quran": "Quran",
  "Injil": "Bible",
  "Weda": "Vedas",
  "Tripitaka": "Tripitaka",
  "Hari raya terbesar Hindu adalah?": "What is the biggest Hindu holiday?",
  "Nyepi": "Nyepi",
  "Galungan": "Galungan",
  "Kuningan": "Kuningan",
  "Saraswati": "Saraswati",
  "KMHD singkatan dari?": "What does KMHD stand for?",
  "Keluarga Muda Hindu Dharma": "Young Hindu Dharma Family",
  "Komunitas Mahasiswa Hindu Dharma": "Hindu Dharma Student Community",
  "Keluarga Mahasiswa Hindu Dharma": "Hindu Dharma Student Family",
  "KM Hindu Dharma": "KM Hindu Dharma",
  "Tari Bedhaya adalah tari istana yang berasal dari?": "Bedhaya dance is a palace dance originating from?",
  "Bali": "Bali",
  "Yogyakarta": "Yogyakarta",
  "Surakarta": "Surakarta",
  "Jawa Timur": "East Java",
  "Kostum tari tradisional Jawa biasanya menggunakan?": "Traditional Javanese dance costumes usually use?",
  "Kain batik": "Batik cloth",
  "Kain tenun": "Woven cloth",
  "Kain songket": "Songket cloth",
  "Kain lurik": "Lurik cloth",
  "Gerakan dasar tari Jawa yang paling dikenal adalah?": "What is the most well-known basic movement in Javanese dance?",
  "Ngithing": "Ngithing",
  "Ngembat": "Ngembat",
  "Kebyar": "Kebyar",
  "Tandak": "Tandak",
  "Paduan suara yang menyanyi tanpa iringan alat musik disebut?": "A choir singing without musical instruments is called?",
  "Acapella": "Acapella",
  "Choir": "Choir",
  "Ensemble": "Ensemble",
  "Quartet": "Quartet",
  "Suara tertinggi dalam paduan suara campuran adalah?": "The highest voice in a mixed choir is?",
  "Alto": "Alto",
  "Tenor": "Tenor",
  "Sopran": "Soprano",
  "Bass": "Bass",
  "PSM UGM sering tampil di acara?": "PSM UGM often performs at which events?",
  "Dies Natalis UGM": "UGM Anniversary",
  "Upacara Wisuda": "Graduation ceremony",
  "Kedua-duanya": "Both",
  "Tidak pernah tampil": "Never performs",
  "Mapagama singkatan dari?": "What does Mapagama stand for?",
  "Mahasiswa Pencinta Alam Gadjah Mada": "Gadjah Mada Nature Enthusiast Students",
  "Mahasiswa Pecinta Alam Gadjah Mada": "Gadjah Mada Nature Lover Students",
  "Mahasiswa Penjelajah Alam Gadjah Mada": "Gadjah Mada Nature Explorer Students",
  "Masyarakat Pecinta Alam Gadjah Mada": "Gadjah Mada Nature Lover Community",
  "Prinsip dasar pecinta alam adalah?": "What is the basic principle of nature lovers?",
  "Tinggalkan jejak sebanyak mungkin": "Leave as many traces as possible",
  "Tinggalkan sampahmu di alam": "Leave your trash in nature",
  "Leave no trace — jaga alam": "Leave no trace — protect nature",
  "Bawa pulang flora dan fauna": "Take home flora and fauna",
  "Alat wajib mendaki gunung adalah?": "What is essential equipment for hiking a mountain?",
  "Payung": "Umbrella",
  "Jas hujan dan kompas": "Raincoat and compass",
  "Sepatu kasual": "Casual shoes",
  "Topi pantai": "Beach hat",
  "Prinsip dasar koperasi adalah?": "What is the core principle of a cooperative?",
  "Profit semaksimal mungkin": "Maximum profit",
  "Dari, oleh, dan untuk anggota": "From, by, and for members",
  "Persaingan bebas": "Free competition",
  "Monopoli pasar": "Market monopoly",
  "Koperasi di Indonesia diatur dalam UU nomor?": "Cooperatives in Indonesia are regulated under which law?",
  "UU No. 17/2012": "Law No. 17/2012",
  "UU No. 25/1992": "Law No. 25/1992",
  "UU No. 5/1960": "Law No. 5/1960",
  "UU No. 13/2003": "Law No. 13/2003",
  "SHU koperasi dibagi berdasarkan?": "Cooperative surplus (SHU) is distributed based on?",
  "Modal awal anggota": "Initial member capital",
  "Partisipasi transaksi anggota": "Member transaction participation",
  "Jabatan pengurus": "Management position",
  "Lama bergabung": "Length of membership",
  "Kode etik jurnalistik mengharuskan wartawan untuk?": "The journalistic code of ethics requires reporters to?",
  "Berpihak pada satu pihak": "Take one side",
  "Berimbang dan cover both sides": "Be balanced and cover both sides",
  "Menyembunyikan fakta": "Hide facts",
  "Mengutamakan opini pribadi": "Prioritize personal opinion",
  "Lead (teras berita) yang baik harus mengandung?": "A good lead should contain?",
  "5W1H": "5W1H",
  "Opini redaksi": "Editorial opinion",
  "Iklan produk": "Product advertisement",
  "Biografi penulis": "Author biography",
  "Berita yang menyebarkan informasi palsu disebut?": "News that spreads false information is called?",
  "Breaking news": "Breaking news",
  "Feature": "Feature",
  "Hoaks": "Hoax",
  "Editorial": "Editorial",
  "Basket": "Basketball",
  "Berkuda": "Horse Riding",
  "Voli": "Volleyball",
};

export function translateText(lang: AppLanguage, text: string) {
  if (lang === "id") return text;
  return DYNAMIC_TRANSLATIONS[text] ?? text;
}
